version: '3.9'

services:

  streamlit_app:
    build:
      context: streamlit
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - STREAMLIT_SERVER_PORT=80
    volumes:
      - ./models:/models
      - ./streamlit:/app
    restart: on-failure