version: '3.9'

services:

  evidently_app:
    build:
      context: dashboards
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - FLASK_APP=app.py
    volumes:
      - ./dashboards:/app
    restart: on-failure

  streamlit_app:
    build:
      context: streamlit_ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - STREAMLIT_SERVER_PORT=80
    volumes:
      - ./models:/models
      - ./streamlit_ui:/app
    restart: on-failure